Fix builds (#114)

diff --git a/.github/workflows/package.yaml b/.github/workflows/package.yaml
--- a/.github/workflows/package.yaml
+++ b/.github/workflows/package.yaml
@@ -1,25 +1,92 @@
+# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
 name: Package vscode extension
 
 on:
+  pull_request:
+    branches:
+    - main
+  push:
+    branches:
+    - main
+  workflow_dispatch:
+    inputs:
+      version:
+        description: 'yamlfmt version'
+        type: string
+        #renovate: datasource=github-releases depName=google/yamlfmt
+        default: v0.13.0
   workflow_call:
+    inputs:
+      version:
+        description: 'yamlfmt version'
+        type: string
+        #renovate: datasource=github-releases depName=google/yamlfmt
+        default: v0.13.0
 
 env:
+  # TODO: Renovate node version to match the package version
   node_version: 20
 
 jobs:
+  validations:
+    name: Validations
+    runs-on: ubuntu-latest
+    outputs:
+      VERSION_NUM: ${{ steps.strip.outputs.VERSION_NUM }}
+    steps:
+    - name: Validate version string
+      run: |
+        if [[ ! ${{ inputs.version }} =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+          echo "Invalid version string. Please provide a valid version string in the format v1.2.3"
+          exit 1
+        fi
+    - name: Strip v from version
+      id: strip
+      run: |
+        version=${{ inputs.version }}
+        echo "VERSION_NUM=${version/v/}" >> $GITHUB_OUTPUT
+
   package:
     name: Package vscode extension
     runs-on: ubuntu-latest
+    needs: validations
+    strategy:
+      matrix:
+        os:
+        - os: win32-x64
+          bin: Windows_x86_64
+        - os: win32-arm64
+          bin: Windows_arm64
+        - os: linux-x64
+          bin: Linux_x86_64
+        - os: linux-arm64
+          bin: Linux_arm64
+        - os: darwin-x64
+          bin: Darwin_x86_64
+        - os: darwin-arm64
+          bin: Darwin_arm64
     steps:
-    - uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4
-      with:
-        name: binaries
-        path: /tmp
-
     - name: Checkout extension repo
       uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
       with:
         fetch-depth: 0
+
+    - name: Download yamlfmt binaries from release
+      uses: robinraju/release-downloader@v1.10
+      with:
+        repository: google/yamlfmt
+        tag: ${{ inputs.version }}
+        fileName: 'yamlfmt_${{ needs.validations.outputs.VERSION_NUM }}_${{ matrix.os.bin }}.tar.gz'
+        extract: true
+        token: ${{ secrets.GITHUB_TOKEN }}
+
+    - name: Cleanup bin
+      run: |
+        rm -rf bin/
+        rm -rf yamlfmt_*.tar.gz
+        mkdir bin
+        mv yamlfmt* bin/
+        chmod +x -R bin/
 
     - name: Setup nodejs
       uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
@@ -29,26 +96,12 @@ jobs:
     - name: Npm install
       run: npm install
 
-    - name: Package multi-platforms
+    - name: Package ${{ matrix.os.os }} extension
       shell: bash
-      run: |
-        declare -A map
-        map["win32-x64"]=windows_amd64_v1
-        map["win32-arm64"]=windows_arm64
-        map["linux-x64"]=linux_amd64_v1
-        map["linux-arm64"]=linux_arm64
-        map["darwin-x64"]=darwin_amd64_v1
-        map["darwin-arm64"]=darwin_arm64
-
-        for arch in ${!map[*]}; do
-          rm -rf bin/
-          mv "/tmp/yamlfmt_${map[$arch]}" bin/
-          chmod +x -R bin/
-          npx vsce package --target $arch
-        done
+      run: npx vsce package --target ${{ matrix.os.os }}
 
     - name: Upload artifacts (vsix files)
       uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4
       with:
-        name: packages
+        name: yaml-formatter_${{ needs.validations.outputs.VERSION_NUM }}_${{ matrix.os.os }}.vsix
         path: "*.vsix"
