test: versions & vsix

diff --git a/.github/workflows/package.yaml b/.github/workflows/package.yaml
--- a/.github/workflows/package.yaml
+++ b/.github/workflows/package.yaml
@@ -2,18 +2,55 @@ name: Package vscode extension
 
 on:
   workflow_call:
+    inputs:
+      version:
+        description: 'yamlfmt version'
+        required: true
+        type: string
 
 env:
+  # TODO: Renovate node version to match the package version
   node_version: 20
 
 jobs:
+  validations:
+    name: Validations
+    runs-on: ubuntu-latest
+    steps:
+    - name: Validate version string
+      run: |
+        if [[ ! ${{ inputs.version }} =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+          echo "Invalid version string. Please provide a valid version string in the format v1.2.3"
+          exit 1
+        fi
+    - name: Strip v from version
+      run: echo "VERSION=${version/v/}" >> $GITHUB_ENV
+      env:
+        version: ${{ inputs.version }}
+
   package:
     name: Package vscode extension
     runs-on: ubuntu-latest
+    needs: validations
+    strategy:
+      matrix:
+        os:
+        - os: win32-x64
+          bin: Windows_x86_64
+        - os: win32-arm64
+          bin: Windows_arm64
+        - os: linux-x64
+          bin: Linux_x86_64
+        - os: linux-arm64
+          bin: Linux_arm64
+        - os: darwin-x64
+          bin: Darwin_x86_64
+        - os: darwin-arm64
+          bin: Darwin_arm64
     steps:
     - uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4
       with:
-        name: binaries
+        name: yamlfmt_${{ env.VERSION }}_${{ matrix.os.bin }}
         path: /tmp
 
     - name: Checkout extension repo
@@ -32,20 +69,9 @@ jobs:
     - name: Package multi-platforms
       shell: bash
       run: |
-        declare -A map
-        map["win32-x64"]=windows_amd64_v1
-        map["win32-arm64"]=windows_arm64
-        map["linux-x64"]=linux_amd64_v1
-        map["linux-arm64"]=linux_arm64
-        map["darwin-x64"]=darwin_amd64_v1
-        map["darwin-arm64"]=darwin_arm64
-
-        for arch in ${!map[*]}; do
-          rm -rf bin/
-          mv "/tmp/yamlfmt_${map[$arch]}" bin/
-          chmod +x -R bin/
-          npx vsce package --target $arch
-        done
+        mv "/tmp/yamlfmt*" bin/
+        chmod +x -R bin/
+        npx vsce package --target ${{ matrix.os.os }}
 
     - name: Upload artifacts (vsix files)
       uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4
diff --git a/.github/workflows/yamlfmt-binaries.yaml b/.github/workflows/yamlfmt-binaries.yaml
--- a/.github/workflows/yamlfmt-binaries.yaml
+++ b/.github/workflows/yamlfmt-binaries.yaml
@@ -2,16 +2,38 @@ name: Gather yamlfmt binaries
 
 on:
   workflow_call:
+    inputs:
+      version:
+        description: 'yamlfmt version'
+        required: true
+        type: string
   workflow_dispatch:
-
-env:
-  # renovate: datasource=github-releases depName=google/yamlfmt
-  version: v0.13.0
+    inputs:
+      version:
+        description: 'yamlfmt version'
+        required: true
+        type: string
 
 jobs:
+  validations:
+    name: Validations
+    runs-on: ubuntu-latest
+    steps:
+    - name: Validate version string
+      run: |
+        if [[ ! ${{ inputs.version }} =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+          echo "Invalid version string. Please provide a valid version string in the format v1.2.3"
+          exit 1
+        fi
+    - name: Strip v from version
+      run: echo "VERSION=${version/v/}" >> $GITHUB_ENV
+      env:
+        version: ${{ inputs.version }}
+
   build:
     name: Get yamlfmt binaries
     runs-on: ubuntu-latest
+    needs: validations
     strategy:
       fail-fast: false
       matrix:
@@ -25,14 +47,11 @@ jobs:
         - Windows_i386
         - Windows_x86_64
     steps:
-    - name: Strip v from version
-      run: echo "VERSION=${version/v/}" >> $GITHUB_ENV
-
     - name: Download yamlfmt binaries from release
       uses: robinraju/release-downloader@v1.10
       with:
         repository: google/yamlfmt
-        tag: ${{ env.version }}
+        tag: ${{ inputs.version }}
         fileName: 'yamlfmt_${{ env.VERSION }}_${{ matrix.os }}.tar.gz'
         extract: true
         token: ${{ secrets.GITHUB_TOKEN }}
